spring:
  application:
    name: contract-service
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 0
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  liquibase:
    default-schema: public
    enabled: false
    show-summary: off
  threads:
    virtual:
      enabled: true
  cloud:
    openfeign:
      client:
        config:
          customer:
            url: "http://hello"
springdoc:
  swagger-ui:
    use-root-path: true
server:
  error:
    include-message: always
